language: python
python:
  - "3.6"

cache: 
  pip: true
  directories:
    - .mypy_cache
    - .mystubs/

before_install:
  - ci/before_install.sh

install:
  - ci/install.sh

script:
  - ci/lint.sh
  - ci/build.sh
  - ci/test.sh

